### ISSUE TITLE
Anpassung der Schriftgösse

### ISSUE THREAD

**Issue by mcpaulde** [Snapstromegon/wordclock#1]
Hallo, gibt es, oder wird es in Zunkunft eine Möglichkeit geben die Schrift bzw die Schriftgrösse anzupassen ?

**Comment by Snapstromegon** [comment]
Dies wäre in der wc.html im CSS bereich bereits früher möglich gewesen, doch ich habe gerade die wc_base.css so angepasst, dass man mit der Variable --fontSize die Schriftgröße festlegen kann.

```
:root{
  /*...*/
  --fontSize: 2em;
}
```

Diese kann nun direkt dort, oder im Stylesheet der wc.html wie folgt durch Hinzufügen der Variablendefinition geändert werden.
```
.wc__wrapper{
  height: 100%;
  width: 100vh;
  margin: auto;
  --fontSize: 1em;
}
```
