### ISSUE TITLE
Problem with letterset in DE

### ISSUE THREAD

**Issue by oweitman** [Snapstromegon/wordclock#13]
i have changed the letterset to due problems with values which contains 

**nach vier**

ther are shown without a gap.

  letterSet: [
    ["E","S","T","I","S","T","I","M","E","I","N","E"],
    ["V","I","E","R","T","E","L","A","Z","E","H","N"],
    ["Z","W","A","N","Z","I","G","F","Ü","N","F","N"],
    ["N","A","C","H","V","O","R","D","H","A","L","B"],
    ["D","A","T","Z","W","Ö","L","F","E","I","N","S"],
    ["Z","W","E","I","D","R","E","I","V","I","E","R"],
    ["F","Ü","N","F","S","E","C","H","S","E","L","F"],
    ["E","S","I","E","B","E","N","A","C","H","T","T"],
    ["N","E","U","N","I","Z","E","H","N","U","H","R"]
  ],

i can not make a pull request, because i reworked the code completly
to integrate it in a plugin for iobroker and with use of jquery
https://github.com/oweitman/ioBroker.mytime/blob/master/widgets/mytime/js/mytime.js#L740
https://github.com/oweitman/ioBroker.mytime/blob/master/widgets/mytime/js/wc_langPack_DE.js#L10

**Comment by Snapstromegon** [comment]
First of all thanks for raising the issue.

I adapted the letterset although I didn't use the same as you did to resolve this, but one that I already hat at hand for a new implementation using web components which I didn't backport yet.

Aside from this issue I took a look at what you did with this wordclock and I like seeing it used elsewhere.
I don't have experience working with ioBroker, but I would have probably skipped jQuery for document.querySelector and related DOM APIs, but that's just personal taste.
What I would recommend you, is taking a look at ``` `` ```-Strings in JS (template literals). They would allow you to make multiline Strings without using ```text += ...``` in every line.

If there's a way to make integrating this project into others easier (e.g. by providing web components), feel free to provide ffedback.
