### ISSUE TITLE
Two bugs in wc_langPack_NL.js

### ISSUE THREAD

**Issue by av01d** [Snapstromegon/wordclock#14]
Line 58 is wrong:
```
case 20:
   ret += 'TIEN VOOR HALF ' + hourNames[h - 1];
```
corrected:
```
case 20:
   ret += 'TIEN VOOR HALF ' + hourNames[h == 12 ? 0 : h];
```

Line 73 is wrong:
```
case 45:
   ret += 'KWART OVER ' + hourNames[h % 12];
```
corrected:
```
case 45:
   ret += 'KWART VOOR ' + hourNames[h % 12];
```

**Comment by Snapstromegon** [comment]
Hey,
thanks for that catch - do you want to create a PR for it so your contribution can be under your name or should I do a commit with this?

**Comment by Snapstromegon** [comment]
Hey @av01d
I don't see your correction of line 73 - can you help me out here?

**Comment by av01d** [comment]
`KWART OVER` should be `KWART VOOR`. And it's line 73, not 83.

**Comment by Snapstromegon** [comment]
Ohh of course.

My first question still stands: Do you want to create a PR (so you are named under the github contributers) or should I do a commit with that fix? @av01d

**Comment by av01d** [comment]
Please commit yourself, thanks.
