### ISSUE TITLE
Wrong Time if round is true

### ISSUE THREAD

**Issue by pphlwmarcel** [Snapstromegon/wordclock#15]
In case that round is set to true there is an issue with the time. 
When it comes to rounding to the next full hour the time is set to the actual hour not the next hour.

e.g. 4:58 pm is showing "it's four o clock" instead "it's five o clock" 

![image](https://github.com/Snapstromegon/wordclock/assets/14854093/4b580219-b230-43d7-a584-3cb4b31653da)

**Comment by Snapstromegon** [comment]
Hi, thanks for raising this issue. This should be resolved by the newest commit. Please check and close this issue if it is resolved.

**Comment by pphlwmarcel** [comment]
It's fixed. Thank you :-)
