### ISSUE TITLE
Correcting wc_langPack_CH_BERN

### ISSUE THREAD

**Issue by Jlauper** [Snapstromegon/wordclock#16]
there is an error in the letterset in the Bernese German version. Here is the correct letterset:

wc_addLanguagePack({
  langCode: 'CH_BERN',
  letterSet: [
    ['Ä', 'S', 'M', 'I', 'S', 'C', 'H', 'U', 'F', 'Ü', 'F'],
    ['Z', 'Ä', 'H', 'N', 'Z', 'W', 'Ä', 'N', 'Z', 'G', 'I'],
    ['N', 'A', 'B', 'H', 'V', 'I', 'E', 'R', 'T', 'U', 'L'],
    ['V', 'O', 'R', 'N', 'A', 'B', 'H', 'A', 'U', 'B', 'I'],
    ['E', 'I', 'S', 'S', 'Z', 'W', 'Ö', 'I', 'W', 'E', 'I'],
    ['D', 'R', 'Ü', 'Ü', 'E', 'A', 'V', 'I', 'E', 'R', 'I'],
    ['F', 'Ü', 'F', 'I', 'N', 'S', 'Ä', 'C', 'H', 'S', 'I'],
    ['S', 'I', 'B', 'N', 'I', 'E', 'A', 'C', 'H', 'T', 'I'],
    ['N', 'Ü', 'N', 'I', 'Z', 'Ä', 'H', 'N', 'I', 'L', 'F'],
    ['E', 'U', 'F', 'I', 'F', 'Z', 'W', 'Ö', 'U', 'F', 'I']
  ],

**Comment by Jlauper** [comment]
The problem is that the version on github does not work. With the test.html the time is partially not displayed. With this adjustment it works for me.

**Comment by Snapstromegon** [comment]
Oh; I see.
Thanks for pointing this out and providing a fixed letterset.
