### ISSUE TITLE
Time two hours fast at 0 <= m < 5

### ISSUE THREAD

**Issue by iainfm** [Snapstromegon/wordclock#8]
Hi,

Firstly, thanks for a great wordclock!

I found a small issue with the EN language pack. When the time is between exactly <something> o'clock and 5 past <something> the time displayed was two hours fast. I fixed this by changing case 0 to:

`ret += hourNames[h - 1] + ' OCLOCK';   // was [h + 1]`

I'm not sure if this it the right/best way to fix it, but it seems to have worked.

I also wanted an extra option to have "it is **nearly** half past" etc, so I added:

`if (((m + 1) % 5) == 0) {
	ret += 'NEARLY ';
	m += 1;
}`
	
`if (((m + 2) % 5) == 0) {
	ret += 'NEARLY ';
	m += 2;
}`

above the switch statement, and changed the word/letter matrix accordingly. Again, I'm not sure if there's a better way. :)

**Comment by Snapstromegon** [comment]
Thanks for the feedback, I'll take a look later!

**Comment by Snapstromegon** [comment]
Your solution was exactly correct - I keep this issue open, because I'm considering the "nearly" proposal.

Can you describe that behavior in more detail?
As I understand it, it would do the following:

| Time | Result |
|:-:|:--|
| 10:55 | IT IS FIVE TO ELEVEN |
| 10:56 | IT IS FIVE TO ELEVEN |
| 10:57 | IT IS FIVE TO ELEVEN |
| 10:58 | IT IS FIVE TO ELEVEN |
| 10:59 | IT IS NEARLY ELEVEN OCLOCK |
| 11:00 | IT IS ELEVEN OCLOCK |

If I implement this, I'd like to add a setting for this - do you have an idea what name might fit?
Also feel free to create a PR for this (even if it's just to show the behavior).

**Comment by iainfm** [comment]
Hi,

Yes, that's the idea, but two 'nearly' times: Every 5 minute would look like this:

11:00 IT IS ELEVEN O'CLOCK
11:01 IT IS ELEVEN O'CLOCK
11:02 IT IS ELEVEN O'CLOCK
11:03 IT IS NEARLY FIVE PAST ELEVEN
11:04 IT IS NEARLY FIVE PAST ELEVEN
11:05 IT IS FIVE PAST ELEVEN

I have this running [here](http://mtsltd.lennoxbrewery.com/wordclock/) if you want a look :)

I'd call the setting 'fuzzy time' or something like that. It could be extended to 'times past' as well, eg

11:02 IT HAS JUST GONE ELEVEN O'CLOCK

But perhaps that's going a bit too far!

I'm a bit of a noob at github, but will look at the PR :)

**Comment by iainfm** [comment]
I think I've created a PR, but I'm not sure sorry!

**Comment by Snapstromegon** [comment]
You just created a "fork" (read "copy under your name") of my repository.
This is the first important step to creating a PR.

Next you clone your fork via ```git clone https://github.com/iainfm/wordclock.git```.
Switch into that folder via ```cd wordclock```
Then you create a new branch "fuzzy_time" with ```git checkout -b fuzzy_time``.
Now you make your changes in your local copy.
Push your changes to your fork using ```git push```.
Finally click in github on new pull request and select your fork and the fuzzy_time branch on the one side and my repo with the master branch on the other.

You can see that it worked, When you see your PR when you click in my repo on pull requests.

**Comment by Snapstromegon** [comment]
I just saw that you opened your PR from your repo into your repo -> you need to change the target repo to my repo.
I don't know if this is possible without recreating the PR.

**Comment by iainfm** [comment]
Is that better? :)
